name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: python3.8 -m pip install --upgrade pip

      - name: Install dependencies
        run: python3.8 -m pip install pytest

      - name: Run tests
        run: python3.8 -m pytest